services:
  - type: web
    name: nlp-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: FLASK_SECRET_KEY
        value: your-secret-key-here
      - key: MODEL_URL
        value: your-google-drive-direct-link
      - key: CLOUDINARY_CLOUD_NAME
        value: your-cloud-name
      - key: CLOUDINARY_API_KEY
        value: your-api-key
      - key: CLOUDINARY_API_SECRET
        value: your-secret
